$color = rgba({{ colors.background.default.red }}, {{ colors.background.default.green }}, {{ colors.background.default.blue }}, 1)
$inner_color = rgba({{ colors.surface.default.red }}, {{ colors.surface.default.green }}, {{ colors.surface.default.blue }}, 1)
$outer_color = rgba({{ colors.outline.default.red }}, {{ colors.outline.default.green }}, {{ colors.outline.default.blue }}, 0.5)
$font_color = rgba({{ colors.on_background.default.red }}, {{ colors.on_background.default.green }}, {{ colors.on_background.default.blue }}, 1)
$placeholder_color = rgba({{ colors.on_background.default.red }}, {{ colors.on_background.default.green }}, {{ colors.on_background.default.blue }}, 0.6)
$check_color = rgba({{ colors.primary.default.red }}, {{ colors.primary.default.green }}, {{ colors.primary.default.blue }}, 1.0)
